name = "pwa-push-demo-frontend"
main = ".open-next/worker.js"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:cloudflare"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# 環境変数（公開情報のみ）
[vars]
NEXT_PUBLIC_BFF_URL = "https://pwa-push-demo-bff.fleatoke.workers.dev"
NEXT_PUBLIC_SUPABASE_URL = "https://qcxnwhfmfskaqxryzptz.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjeG53aGZtZnNrYXF4cnl6cHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAwOTA2NzcsImV4cCI6MjA0NTY2NjY3N30.LG8xqF1kqpGmqfJxgwEDnNfVS4cZ3v-WkU3P8fCt8RM"
NEXT_PUBLIC_VAPID_PUBLIC_KEY = "BGiIDYRNL-sa7Dp8UGYuf0ICZ4voSM7xKckuqyGB1N13fQyzeibls2ohvQqWiOumcQ9sV0mPPRtiCSgDLxfe3sg"

