import { Hono } from 'hono';

// NOTE: Before running `wrangler dev`, a human operator must set OPENAI_API_KEY
// using `wrangler secret put OPENAI_API_KEY`. Do not commit actual secrets.

type Bindings = {
  OPENAI_API_KEY?: string;
};

const AUDIO_FIELD = 'audio';
const TRANSCRIBE_MODEL = 'gpt-4o-transcribe';
const MDX_MODEL = 'gpt-4o-mini';
const OPENAI_BASE_URL = 'https://api.openai.com/v1';

const app = new Hono<{ Bindings: Bindings }>();

app.post('/api/audio-blog', async (c) => {
  const apiKey = c.env.OPENAI_API_KEY;
  if (!apiKey) {
    return c.text(
      'Missing OPENAI_API_KEY binding. Set it locally with `wrangler secret put OPENAI_API_KEY`.',
      500
    );
  }

  const formData = await c.req.formData();
  const audioFile = formData.get(AUDIO_FIELD);

  if (!(audioFile instanceof File)) {
    return c.text('Expected multipart field "audio" containing a file.', 400);
  }

  try {
    const transcript = await transcribeAudio(audioFile, apiKey);
    if (!transcript?.trim()) {
      throw new Error('Transcription response was empty.');
    }

    const mdx = await generateMdxFromTranscript(transcript, apiKey);
    return c.text(mdx.trim());
  } catch (error) {
    console.error('audio-blog worker', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    return c.text(`Audio blog worker error: ${message}`, 500);
  }
});

async function transcribeAudio(file: File, apiKey: string): Promise<string> {
  const form = new FormData();
  form.append('model', TRANSCRIBE_MODEL);
  form.append('file', file, file.name || 'recording.webm');

  const response = await fetch(`${OPENAI_BASE_URL}/audio/transcriptions`, {
    method: 'POST',
    headers: buildAuthHeaders(apiKey),
    body: form,
  });

  if (!response.ok) {
    const errorBody = await response.text().catch(() => '');
    throw new Error(`Transcription failed: ${response.status} ${errorBody}`);
  }

  const payload = (await response.json()) as { text?: string };
  return payload.text ?? '';
}

async function generateMdxFromTranscript(transcript: string, apiKey: string): Promise<string> {
  const isoDate = new Date().toISOString().split('T')[0] ?? '2025-01-01';

  const systemPrompt =
    'You are an assistant that turns clean transcripts into polished MDX blog articles with YAML frontmatter.';

  const response = await fetch(`${OPENAI_BASE_URL}/chat/completions`, {
    method: 'POST',
    headers: {
      ...buildAuthHeaders(apiKey),
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: MDX_MODEL,
      temperature: 0.7,
      messages: [
        { role: 'system', content: systemPrompt },
        {
          role: 'user',
          content:
            'Use the transcript below to write an MDX article. Follow this format exactly:\n' +
            '---\n' +
            'title: <concise title>\n' +
            `date: ${isoDate}\n` +
            'summary: <2 sentences>\n' +
            'tags:\n' +
            '  - audio\n' +
            '  - autogenerated\n' +
            '---\n\n' +
            '## Introduction\n' +
            '<hook paragraph>\n\n' +
            '## Key Ideas\n' +
            '- bullet list with highlights\n\n' +
            '## Takeaways\n' +
            'Short closing paragraph.\n\n' +
            'Transcript:\n\n' +
            transcript,
        },
      ],
    }),
  });

  if (!response.ok) {
    const errorBody = await response.text().catch(() => '');
    throw new Error(`MDX generation failed: ${response.status} ${errorBody}`);
  }

  const payload = (await response.json()) as {
    choices?: { message?: { content?: string } }[];
  };
  const mdx = payload.choices?.[0]?.message?.content;
  if (!mdx) {
    throw new Error('MDX generation returned no content.');
  }

  return mdx;
}

function buildAuthHeaders(apiKey: string) {
  return {
    Authorization: `Bearer ${apiKey}`,
  };
}

export default app;
