name = "pwa-push-demo-bff"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Workers の設定
workers_dev = true

# CORS設定用
[vars]
# 本番のフロントエンドURLを設定
ALLOWED_ORIGINS = "http://localhost:3001,https://pwa-push-demo-frontend.fleatoke.workers.dev"

# 環境変数は .dev.vars に記載（このファイルは .gitignore に追加）
# SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY
# FCM_PROJECT_ID
# FCM_CLIENT_EMAIL
# FCM_PRIVATE_KEY

