name = "pwa-push-demo-bff"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Workers の設定
workers_dev = true

# CORS設定用
[vars]
# 本番環境では適切なオリジンに変更
ALLOWED_ORIGINS = "http://localhost:3000,https://your-frontend.vercel.app"

# 環境変数は .dev.vars に記載（このファイルは .gitignore に追加）
# SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY
# VAPID_PUBLIC_KEY
# VAPID_PRIVATE_KEY
# VAPID_MAILTO

